version: "3.9"

services:
  prueba_django:
    image: python:3.9.5
    container_name: prueba_djangoISDM
    restart: always
    volumes:
      - type: bind
        source: .
        target: /opt/back_end
    ports:
        - "8000:8000"
    stdin_open: true
    tty: true
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=dbsql        
      - MYSQL_USER=colquee
      - MYSQL_PASSWORD=killzone2018

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:      
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbsql
      MYSQL_USER: colquee
      MYSQL_PASSWORD: killzone2018
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    
